server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:sqlite:activities.db?journal_mode=WAL&synchronous=NORMAL
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1      
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

app:
  storage:
    location: ./storage/tcx
  user:
    max-hr: 185 # Pulsaciones máximas por defecto para zonas FC
  elevation:
    min-threshold-meters: 0.1 # Umbral de histeresis para filtrar ruido GPS en elevación

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

